name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:    
    name: Build container image
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login registry
      uses: docker/login-action@v1
      with:
          service_principal: "service_principal_name"
          service_principal_password: "Zgj8Q~u2_LErctPkOuJ03Ghcv31EIqUkwwOkZb2U"
          tenant: "d110c826-4e7b-4e0b-9090-2e63efaa6945"
          registry: "testdevcontainer.azurecr.io"
          repository: "testdevcontainer"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
